### PR TITLE
Backed enum support

### LINKED ISSUE #34: Backed-Enum support
During my implementation, I realized the need for enums. However, I ended up just using a string in the DTO instead.

StringBacked and IntegerBacked enums could be a `Castable` type. Implementation could be by using `tryFrom` (or `from` if `required` is true) right before the hydration of value.

Since we're using 8.1, supporting enums could be a positive thing.

Let me know what you think. I can try and help.

### PR DESCRIPTION
**Pull request by jacyimp**
PR for issue #34

It's missing tests. I don't have experience with Pest. Gotta get around to learn it.

I could've implemented inside `CastTo` but it ended up cluttering a lot; Makes more sense to be an independent `Castable`

Let me know how to proceed, and thanks!

### CODE REVIEW

**Comment by jacyimp** [comment]
The fourth example now has a backed string enum, but that's all the test I've done.

If everything else is alright, I'll get down to writing tests. (?)

**Comment by BennyC** [comment]
> The fourth example now has a backed string enum, but that's all the test I've done.
> 
> If everything else is alright, I'll get down to writing tests. (?)

Looks pretty good to me at a quick glance. Some tests would be great and then I think its good to go! Thanks again for contributing! 🎉

**Comment by jacyimp** [comment]
Found out that due to strict_type, the int-backed enums were failing. Had to use reflection. Got nowhere with `IntBackedEnum` interface; Apparently, it's an internal-usage interface not for userland.

Added 2 new properties to `pet.xml` fixture for enum (int and string backed).

Let me know if anything feels off.

Thanks!

**Comment by BennyC** [comment]
@jacyimp Sorry I've taken so long to merge this! It's been an extremely hectic start to the year!

**Pull request merged**
